[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "1.0.0-alpha1"
license = "MIT"
edition = "2024"
rust-version = "1.93"
repository = "https://github.com/VVAT3R/legion-linux-toolkit"

[workspace.dependencies]
slint = { version = "1.17", default-features = false }
slint-build = "1.17"
ksni = "0.3"
zbus = { version = "5", default-features = false, features = ["tokio"] }
zbus_polkit = "5"
logind-zbus = "5"
clap = { version = "4", features = ["derive"] }
thiserror = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros", "signal", "time"] }
rustix = { version = "1", features = ["event", "fs"] }
log = "0.4"
env_logger = "0.11"
tempfile = "3"
assert_cmd = "2"
